name: tanzania_geo_data_example
description: Demonstrates how to use the tanzania_geo_data package.
publish_to: 'none'

environment:
  sdk: ^3.11.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  tanzania_geo_data:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
